version: "2"
services:
  distil:
    build: .
    ports:
      - 45042:45042
    environment:
      - D3MSTATICDIR=/static
    volumes:
      - ./seed_datasets_current:/seed_datasets_current
      - ./static:/static
  dummy-ta3:
    image: registry.gitlab.com/datadrivendiscovery/dummy-ta3/dummy-ta3:2019.4.11
    environment:
      - DATASET=${DATASET}
    command: ["/usr/bin/python3", "-m", "dummy_ta3.dummy_ta3", "-p", "/seed_datasets_current/$DATASET/TRAIN/problem_TRAIN/problemDoc.json", "-d", "/seed_datasets_current", "-e", "distil", "-t", "600"]
    links:
      - "distil"
    volumes:
      - ./seed_datasets_current:/seed_datasets_current
