version: "2"
services:
  exline:
    build: .
    ports:
      - 45042:45042
    volumes:
      - ./seed_datasets_current:/seed_datasets_current
      - ./exline:/app/exline
      - ./server:/app/server
      - ./main.py:/app/main.py
      - ./config.py:/app/config.py
  dummy-ta3:
    image: new-dummy
    command: ["/usr/bin/python3", "-m", "dummy_ta3.dummy_ta3", "-p", "/seed_datasets_current/49_facebook/TRAIN/problem_TRAIN/problemDoc.json", "-d", "/seed_datasets_current", "-e", "exline", "-t", "300"]
    links:
      - "exline"
    volumes:
      - ./seed_datasets_current:/seed_datasets_current
